#!/usr/bin/env bash
# ===========================================================================
#  repro/table2.sh  --  reproduce the "Ours(eps)" rows of Table 2
#
#  Usage
#      bash repro/table2.sh                    all six examples
#      bash repro/table2.sh eg1 eg5            only those examples
#      EPS="1.0 0.5 0.1 0.02" bash repro/table2.sh eg1
#      METHOD=2 bash repro/table2.sh           method=2 (Split only)
#
#  For each example and horizon H the table reports
#
#      B1 = (mid) +- (half-width)   the bounding box Box(C) of the cover C
#      rho                          wmax(B1) / wmax(B1 at eps = 1.0)
#      time (s) | #(C)              wall clock and the number of boxes in C
#
#  exactly as in Table 2 of the paper (the "Ours(1.0/0.5/0.1)" rows).
#  Results are written to repro/out/table2.txt and repro/out/table2.tex;
#  compare them with repro/table2_paper.txt.
#
#  The default (method=0) is the Refine of Section 5; METHOD / STEPB / ORDER
#  select the other settings, see README section 3.2.
#
#  NOTE the timings depend on the machine.  The paper used a 13th Gen Intel
#  Core i7-13700HX at 2.10 GHz with 16 GB RAM.
# ===========================================================================
set -u

cd "$(dirname "$0")/.." || exit 1
BIN=./EnCorelib
[ -x "$BIN" ] || BIN=./EnCorelib.exe
[ -x "$BIN" ] || BIN=./bin/EnCorelib.exe
if [ ! -x "$BIN" ]; then echo "build first (or use bin/):  make" >&2; exit 1; fi

EPS=${EPS:-"1.0 0.5 0.1"}
METHOD=${METHOD:-0}
STEPB=${STEPB:-0}
ORDER=${ORDER:-20}

OUT=repro/out
mkdir -p "$OUT"
TXT=$OUT/table2.txt
TEX=$OUT/table2.tex

# --- the six problems of Table 1 -------------------------------------------
#      tag | name | n | vars | rhs | initial box (lo hi pairs) | horizons
eg1="Eg1|Lotka-Volterra|2|x y|2*x-2*x*y -y+x*y|0.9 1.1 2.9 3.1|4 5.5"
eg2="Eg2|VanDerPol|2|x y|y (1-x^2)*y-x|-3.1 -2.9 2.9 3.1|1 2"
eg3="Eg3|Quadratic|2|x y|y x^2|0.95 1.05 -1.05 -0.95|1 4"
eg4="Eg4|FitzHugh|2|x y|x-x^3/3-y+0.5 0.08*(x+0.7-0.8*y)|0.9 1.1 -0.1 0.1|1 4"
eg5="Eg5|Lorenz|3|x y z|10*(y-x) x*(28-z)-y x*y-8*z/3|14.999 15.001 14.999 15.001 35.999 36.001|1 4"
eg6="Eg6|Roessler|3|x y z|-y-z x+0.2*y 0.2+z*(x-5.7)|0.9 1.1 1.9 2.1 2.9 3.1|1 4"

WANT=${*:-"eg1 eg2 eg3 eg4 eg5 eg6"}

FMT='%-5s %-15s %-5s %-5s  %-44s %-6s %-9s %s\n'
RULE='---------------------------------------------------------------------------------------------------------'

emit() { printf "$FMT" "$@" | tee -a "$TXT"; }

{
  echo "# Table 2 (the Ours(eps) rows) -- regenerated $(date '+%Y-%m-%d %H:%M:%S')"
  echo "# method=$METHOD  stepB=$STEPB  order=$ORDER  eps in { $EPS }"
  echo
} > "$TXT"

{
  echo "% generated by repro/table2.sh"
  echo "\\begin{tabular}{llrrlrrr}"
  echo "\\hline"
  echo "Case & Name & \$H\$ & \$\\varepsilon\$ & \$B_1\$ & \$\\rho\$ & Time (s) & \$\\#(C)\$ \\\\"
  echo "\\hline"
} > "$TEX"

printf "$FMT" Case Name eps H "B1 = (mid) +- (half-width)" rho "time (s)" "#(C)" | tee -a "$TXT"
printf '%s\n' "$RULE" | tee -a "$TXT"

for key in $WANT; do
  spec=$(eval "printf '%s' \"\${$key:-}\"")
  if [ -z "$spec" ]; then echo "unknown example: $key" >&2; continue; fi
  IFS='|' read -r tag name dim vars rhs box horizons <<EOF
$spec
EOF

  for H in $horizons; do
    base_w=""
    for e in $EPS; do
      out=$("$BIN" 2 0 "$METHOD" "$STEPB" 0 "$dim" $vars $rhs "$e" "$ORDER" "$H" 0 $box 2>&1)
      hull=$(printf '%s' "$out" | sed -n 's/^Hull(T=[^)]*)=//p')
      w=$(   printf '%s' "$out" | sed -n 's/^wmax(B1)=//p')
      nc=$(  printf '%s' "$out" | sed -n 's/^#(C)=\([0-9]*\).*/\1/p')
      ms=$(  printf '%s' "$out" | sed -n 's/^time(ms)=//p')

      if [ -z "$hull" ]; then
        emit "$tag" "$name" "$e" "$H" "FAILED (see stderr)" "-" "-" "-"
        continue
      fi

      # {[a, b],[c, d],...}  ->  "(mid,...) +- (half,...)" rounded to 2 places
      b1r=$(printf '%s' "$hull" | tr -d '{}[]' | awk -F, '
        function r2(v,   s) { s = sprintf("%.2f", v); return (s == "-0.00") ? "0.00" : s }
        { half=""; mid="";
          for (i = 1; i <= NF; i += 2) {
            lo = $i + 0; hi = $(i+1) + 0;
            mid  = mid  (i > 1 ? ", " : "") r2((lo+hi)/2);
            half = half (i > 1 ? ", " : "") r2((hi-lo)/2);
          }
          printf "(%s) +- (%s)", mid, half }')

      [ -z "$base_w" ] && base_w=$w
      rho=$( awk -v a="$w"  -v b="$base_w" 'BEGIN{ if (b>0) printf "%.2f", a/b; else printf "-" }')
      secs=$(awk -v m="$ms" 'BEGIN{ printf "%.2f", m/1000 }')

      emit "$tag" "$name" "$e" "$H" "$b1r" "$rho" "$secs" "$nc"
      printf '%s & %s & %s & %s & $%s$ & %s & %s & %s \\\\\n' \
             "$tag" "$name" "$H" "$e" "$(printf '%s' "$b1r" | sed 's/+-/\\pm/')" \
             "$rho" "$secs" "$nc" >> "$TEX"
    done
    printf '\n' | tee -a "$TXT"
  done
  echo "\\hline" >> "$TEX"
done

echo "\\end{tabular}" >> "$TEX"
echo "written: $TXT  and  $TEX"
echo "paper values for comparison: repro/table2_paper.txt"
